@startuml
hide members
hide circle
skinparam shadowing false
skinparam ClassFontSize 16
skinparam ClassFontName Arial

class Stage
class AnchorPane
class ScrollPane
class VBox
class ImageView
class Label

AnchorPane -up-> Stage
ScrollPane -up-> AnchorPane

TextField -up-> AnchorPane
Button -up-> AnchorPane

VBox -up-> ScrollPane
ImageView -up-> VBox
Label -up-> VBox
@enduml
