@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

-> logic : execute("edit 1 n/Alice Yeoh")
activate logic
logic -> abp ++: parseCommand("edit 1 n/Alice Yeoh")
create ecp
abp -> ecp
activate ecp
ecp --> abp
deactivate ecp
abp -> ecp ++: parse("1 n/Alice Yeoh")
create ec
ecp -> ec ++: 1, editPersonDescriptor
ec --> ecp --
ecp --> abp --: command
ecp -[hidden]-> abp --: command
destroy ecp


abp --> logic --: command

logic -> ec : execute
activate ec
ec --> logic : commandResult
deactivate ec
ec -[hidden]-> logic : commandResult
destroy ec

<-- logic :commandResult
deactivate logic

@enduml
