@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> abp ++: parseCommand(edit 1 n/Alice Yeoh)
create ecp
abp -> ecp
abp -> ecp ++: parse(1 n/Alice Yeoh)
create ec
ecp -> ec ++: 1, n/Alice Yeoh
ec --> ecp --
ecp --> abp --: command
abp --> logic --: command
[<-- logic

@enduml
