@startuml

hide footbox
skinparam sequenceReferenceBackgroundColor #f7807c

actor Player

participant ":TextUi" as TextUi #EE82EE
participant ":MSLogic" as MSLogic #90EE90

Player -> TextUi : mark x y
TextUi -> MSLogic : markCellAt(x, y)
return

ref over TextUi, MSLogic
    get minefield appearance
end ref

TextUi --> Player : Show updated minefield

@enduml
